-- Volcando estructura de base de datos para EMAILSEND
CREATE DATABASE IF NOT EXISTS `EMAILSEND` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;
USE `EMAILSEND`;

-- Volcando estructura para tabla EMAILSEND.CORREOS
CREATE TABLE IF NOT EXISTS `CORREOS` (
  `CORREOID` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(100) NOT NULL,
  `CORREO` varchar(1000) NOT NULL,
  `ASUNTO` varchar(100) NOT NULL,
  `SALUDO` varchar(50) NOT NULL,
  `CUERPO` text NOT NULL,
  `ESTADO` char(1) DEFAULT 'P',
  `CREACION` timestamp NOT NULL DEFAULT current_timestamp(),
  `ACTUALIZACION` TIMESTAMP NULL,
  PRIMARY KEY (`CORREOID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Volcando estructura para tabla EMAILSEND.USUARIOS
CREATE TABLE IF NOT EXISTS `USUARIOS` (
  `USUARIOID` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(150) NOT NULL,
  `CORREOLOGIN` varchar(150) NOT NULL,
  `CLAVELOGIN` varchar(250) NOT NULL,
  `CORREOENVIO` varchar(150) NOT NULL,
  `CLAVEENVIO` varchar(250) NOT NULL,
  `RESETCLAVE` char(1) DEFAULT '0',
  `CREACION` timestamp NOT NULL DEFAULT current_timestamp(),
  `ACTUALIZACION` TIMESTAMP NULL,
  PRIMARY KEY (`USUARIOID`),
  UNIQUE KEY `CORREOLOGIN` (`CORREOLOGIN`),
  UNIQUE KEY `CORREOENVIO` (`CORREOENVIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- Volcando estructura para tabla EMAILSEND.NOMBRESGRUPOSEXCEL
CREATE TABLE IF NOT EXISTS `NOMBRESGRUPOSEXCEL` (
  `NGEID` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRES` varchar(100) NOT NULL,
  `ESTADO` char(1) DEFAULT 'A',
  `USUARIOID` int(11) NOT NULL,
  PRIMARY KEY (`NGEID`),
  UNIQUE KEY `NOMBRES` (`NOMBRES`),
  KEY `FK_NGE_USUARIOS` (`USUARIOID`),
  CONSTRAINT `FK_NGE_USUARIOS` FOREIGN KEY (`USUARIOID`) REFERENCES `USUARIOS` (`USUARIOID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE `NOMBRESGRUPOSEXCEL` ADD
IMAGEN VARCHAR(100) NULL;

-- ALTER TABLE NOMBRESGRUPOSEXCEL DROP INDEX NOMBRES;

-- Volcando estructura para tabla EMAILSEND.SOLICITUDENVIARCORREOS
CREATE TABLE IF NOT EXISTS `SOLICITUDENVIARCORREOS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USUARIOID` int(11) NOT NULL,
  `NGEID` int(11) NOT NULL,
  `ESTADO` char(1) DEFAULT 'I',
  `CREACION` timestamp NOT NULL DEFAULT current_timestamp(),
  `ACTUALIZACION` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- Volcando estructura para tabla EMAILSEND.USUARIOSCORREOS
CREATE TABLE IF NOT EXISTS `USUARIOSCORREOS` (
  `UCID` int(11) NOT NULL AUTO_INCREMENT,
  `NGEID` int(11) NOT NULL,
  `USUARIOID` int(11) NOT NULL,
  `CORREOID` int(11) NOT NULL,
  PRIMARY KEY (`UCID`),
  KEY `FK_USUARIOCORREOS_NGE` (`NGEID`),
  KEY `FK_USUARIOCORREOS_USUARIOS` (`USUARIOID`),
  KEY `FK_USUARIOCORREOS_CORREOS` (`CORREOID`),
  CONSTRAINT `FK_USUARIOCORREOS_CORREOS` FOREIGN KEY (`CORREOID`) REFERENCES `CORREOS` (`CORREOID`),
  CONSTRAINT `FK_USUARIOCORREOS_NGE` FOREIGN KEY (`NGEID`) REFERENCES `NOMBRESGRUPOSEXCEL` (`NGEID`),
  CONSTRAINT `FK_USUARIOCORREOS_USUARIOS` FOREIGN KEY (`USUARIOID`) REFERENCES `USUARIOS` (`USUARIOID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
