<?php

include './conexion.php';
if (!isset($_SESSION)) {
    session_start();
}
$usuarioId = $_SESSION["campoId"];
// $GrupoId = $_SESSION["grupoId"];

// $query = "SELECT NGE.NGEID AS CAMPAÑAID, NGE.USUARIOID AS USUARIOID, NGE.NOMBRES AS NOMBRE,
// C.ESTADO AS ESTADO,UC.NGEID AS NGEID, NGE.IMAGEN AS IMAGEN FROM NOMBRESGRUPOSEXCEL NGE
// INNER JOIN USUARIOSCORREOS UC
// ON NGE.NGEID = UC.NGEID
// INNER JOIN CORREOS C
// ON UC.CORREOID = C.CORREOID
// WHERE NGE.USUARIOID = :id AND C.ESTADO = 'P'
// GROUP BY NGE.NOMBRES, C.ESTADO;";
$query = "SELECT NGE.NGEID AS CAMPAÑAID, NGE.USUARIOID AS USUARIOID, NGE.NOMBRES AS NOMBRE,
C.ESTADO AS ESTADO,UC.NGEID AS NGEID, NGE.IMAGEN, SEC.ESTADO AS ESTADOSOLICITUD FROM NOMBRESGRUPOSEXCEL NGE
INNER JOIN USUARIOSCORREOS UC
ON NGE.NGEID = UC.NGEID
INNER JOIN CORREOS C
ON UC.CORREOID = C.CORREOID
INNER JOIN SOLICITUDENVIARCORREOS SEC
ON NGE.NGEID = SEC.NGEID 
WHERE NGE.USUARIOID = :id AND C.ESTADO = 'P' AND NGE.ESTADO = 'A'
GROUP BY NGE.NOMBRES, C.ESTADO;
";
$statement = $conexion->prepare($query);
$statement->bindParam(":id", $usuarioId, PDO::PARAM_INT);
$statement->execute();
$resultado = $statement->fetchAll(PDO::FETCH_OBJ);
$statement->closeCursor();
if ($statement->rowCount() > 0) {
    echo json_encode($resultado);
} else {
    echo 0;
}
